# Generated by Django 5.2.5 on 2025-08-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('superadmin', 'SuperAdmin'), ('ngoadmin', 'NGO Admin'), ('volunteer', 'Volunteer')], default='donor', max_length=20),
        ),
    ]
